name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - preview-test
      - main # This workflow will run on pushes to either 'preview-test' or 'main'

permissions:
  contents: read
  pages: write
  id-token: write # These permissions are necessary for GitHub Pages deployment actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Checks out your repository code

      - name: Install mdBook if missing
        run: | # Installs mdBook if it's not already available on the runner
          if ! command -v mdbook >/dev/null; then
            echo "mdbook not found, installing..."
            cargo install mdbook --version "^0.4" # Installs a compatible version of mdBook
          else
            echo "mdbook is already installed"
          fi

      - name: Build mdBook
        run: mdbook build docs # This command builds your mdBook.
                               # It expects your mdBook source (src/, SUMMARY.md) to be in the 'docs' directory.
                               # By default, it will output the compiled book to 'docs/book'.

      # --- DEBUGGING STEPS START HERE ---
      # These steps are added to help diagnose why 'docs/book' might not be found.
      # After running, check the logs for these steps to see the directory contents.
      - name: Debug: List contents of 'docs' directory
        run: ls -F docs/ # Lists all files and directories directly inside 'docs/'
        # Expected output here should include 'book/' if the build was successful.

      - name: Debug: List contents of 'docs/book' directory
        run: ls -F docs/book/ # Lists all files and directories inside 'docs/book/'
        # This step will fail if 'docs/book' does not exist, which confirms the problem.
        # If it exists, you should see your compiled HTML files here.
      # --- DEBUGGING STEPS END HERE ---

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5 # Sets up the GitHub Pages environment for deployment.
                                         # This is required by actions/deploy-pages.

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3 # Uploads the built book as an artifact.
        with:
          path: docs/book # The path to the directory containing your built book files.
                          # This must match the output of 'mdbook build docs'.

  deploy:
    needs: build-and-deploy # Ensures this job only runs after 'build-and-deploy' completes successfully
    runs-on: ubuntu-latest # Specifies the operating system for the job
    environment:
      name: github-pages # The standard environment name for GitHub Pages deployments
      url: ${{ steps.deployment.outputs.page_url }} # Gets the URL of the deployed site

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Deploys the uploaded artifact to GitHub Pages.
                                     # Using v4 for the latest features and stability.
